services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    platform: ${APP_PLATFORM:-linux/amd64}
    container_name: app1
    hostname: app1
    environment:
      - APP_ROLE=api
      - PORT=4001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tasrinha_dev
      - DB_POOL_SIZE=1
      - DB_POOL_COUNT=1
      - PAYMENT_QUEUE_NODE=worker1@worker1
      - RELEASE_DISTRIBUTION=sname
      - RELEASE_NODE=app1
      - RELEASE_COOKIE=rinha-cluster
      - ERL_AFLAGS=+S 1:1
      - ERL_FLAGS=+sbwt none +sbwtdcpu none +sbwtdio none
      - ERL_FULLSWEEP_AFTER=10
      - LOG_LEVEL=warning
      - API_BANDIT_ACCEPTORS=1
      - API_BANDIT_MAX_CONN=200
      - API_CONN_KEEPALIVE_MS=3000
      - QUEUE_SOFT_LIMIT=9000
      - QUEUE_HARD_LIMIT=10000
      - ENQUEUE_TIMEOUT_MS=60
    ports:
      - "4001:4001"
    expose:
      - "4001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet
      - payment-processor
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "75MB"

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    platform: ${APP_PLATFORM:-linux/amd64}
    container_name: app2
    hostname: app2
    environment:
      - APP_ROLE=api
      - PORT=4002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tasrinha_dev
      - DB_POOL_SIZE=1
      - DB_POOL_COUNT=1
      - PAYMENT_QUEUE_NODE=worker1@worker1
      - RELEASE_DISTRIBUTION=sname
      - RELEASE_NODE=app2
      - RELEASE_COOKIE=rinha-cluster
      - ERL_AFLAGS=+S 1:1
      - ERL_FLAGS=+sbwt none +sbwtdcpu none +sbwtdio none
      - ERL_FULLSWEEP_AFTER=10
      - LOG_LEVEL=warning
      - API_BANDIT_ACCEPTORS=1
      - API_BANDIT_MAX_CONN=200
      - API_CONN_KEEPALIVE_MS=3000
      - QUEUE_SOFT_LIMIT=9000
      - QUEUE_HARD_LIMIT=10000
      - ENQUEUE_TIMEOUT_MS=60
    ports:
      - "4002:4002"
    expose:
      - "4002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet
      - payment-processor
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "75MB"

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    platform: ${APP_PLATFORM:-linux/amd64}
    container_name: worker1
    hostname: worker1
    environment:
      - APP_ROLE=worker
      - RELEASE_DISTRIBUTION=sname
      - RELEASE_NODE=worker1
      - RELEASE_COOKIE=rinha-cluster
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tasrinha_dev
      - DB_POOL_SIZE=6
      - DB_POOL_COUNT=1
      #- DB_QUEUE_TARGET_MS=2000
      #- DB_QUEUE_INTERVAL_MS=4000
      #- PAYMENT_QUEUE_MAX_SIZE=10000
      #- PAYMENT_QUEUE_SOFT_SIZE=9000
      - ERL_AFLAGS=+S 2:2
      - ERL_FLAGS=+sbwt none +sbwtdcpu none +sbwtdio none
      - ERL_FULLSWEEP_AFTER=10
      - LOG_LEVEL=warning
      - WORKER_CONCURRENCY=12
      - PRIMARY_URL=http://payment-processor-default:8001/payments
      - FALLBACK_URL=http://payment-processor-fallback:8002/payments
      #- PRIMARY_CONNECT_MS=200
      #- PRIMARY_RECV_MS=600
      #- FALLBACK_CONNECT_MS=200
      #- FALLBACK_RECV_MS=500
      #- FINCH_POOL_SIZE=8
      #- FINCH_POOL_COUNT=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "130MB"

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app1
      - app2
      - worker1
    ports:
      - "9999:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - appnet
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasrinha_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "45MB"

networks:
  payment-processor:
    external: true
  appnet:
    driver: bridge

volumes:
  pgdata:
    driver: local
