services:
  app1:
    image: elixir:1.18-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - ${HOME}/.mix:/root/.mix:ro
    container_name: app1
    environment:
      - MIX_ENV=dev
      - PORT=4001
      - MIX_HOME=/root/.mix
      - HEX_OFFLINE=1
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tasrinha_dev
    command: >-
      sh -lc "mix run --no-halt"
    expose:
      - "4001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet
      - payment-processor
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "104MB"

  app2:
    image: elixir:1.18-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - ${HOME}/.mix:/root/.mix:ro
    container_name: app2
    environment:
      - MIX_ENV=dev
      - PORT=4002
      - MIX_HOME=/root/.mix
      - HEX_OFFLINE=1
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tasrinha_dev
    command: >-
      sh -lc "mix run --no-halt"
    expose:
      - "4002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet
      - payment-processor
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "104MB"

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app1
      - app2
    ports:
      - "9999:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - appnet
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "27MB"

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasrinha_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  payment-processor:
    external: true
  appnet:
    driver: bridge

volumes:
  pgdata:
    driver: local
